Fix `@history` when full history is empty.
plone/plone.restapi pull request #1114
Opened 2021-04-28 14:36 UTC by deiferni

The re-used viewlet returns `None` in its `fullHistory` when there is no (visible) workflow history and when there is no (visible) revision history.

We did not take this into account and always attempt to iterate the returned value, which will fail for `None` for obvious reasons.

I'm adding a simple fix for the issue by initializing the value to an empty list in such cases.

Fixes #1113

2021-04-28 14:36 UTC, mister-roboto commented
@deiferni thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-04-29 01:04 UTC, tisto requested changes
@deiferni thanks for the PR! LGTM. Just run black on your PR to fix the failing CI.

2021-04-29 01:08 UTC, tisto commented
@deiferni the black issue might be unrelated to your PR actually. Will look into it. Feel free to run black on your PR anyways though to speed up things if you want.

2021-04-29 01:27 UTC, tisto commented
@deiferni I fixed black in master. Can you please rebase?

2021-04-29 09:13 UTC, deiferni commented
@jenkins-plone-org please run jobs

2021-04-29 10:14 UTC, deiferni commented
@jenkins-plone-org please run jobs

2021-04-29 11:08 UTC, deiferni commented
@tisto thanks, rebased and all tests green. please let me know if anything else comes up and i will amend.

2021-04-30 04:10 UTC, tisto approved these changes

2021-04-30 04:10 UTC, merged

2021-04-30 04:14 UTC, tisto commented
@deiferni thanks for you swift response! Released: https://pypi.org/project/plone.restapi/7.3.4/#id1