Add collective.zpretty integration
plone/plone.restapi pull request #1120
Opened 2021-05-08 06:00 UTC by tiberiuichim

2021-05-08 06:00 UTC, mister-roboto commented
@tiberiuichim thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-05-08 06:10 UTC, tiberiuichim commented
@tisto what are the targets for this PR? We now have Github workflow that tests code for zpretty-based diffs.

Should I add a precommit hook that automatically formats zcml files?

2021-05-08 08:29 UTC, tisto commented
@tiberiuichim a pre-commit hook would be nice to have. I am still somehow experimenting with the CI pipeline on gh actions and I recently started to have doubts about the future of p.r.codeanalysis. Even though I wrote that recipe it does not really fit the gh actions style that we currently start to follow (multiple small jobs). Therefore we could add a zpretty pre-commit hook to the recipe but I am not sure if that's a long term perspective. 

How long does zpretty take on the p.restapi code? It is important that pre-commit hooks run fast...

2021-05-12 16:57 UTC, sneridagh approved these changes

2021-05-13 10:06 UTC, tisto requested changes
@tiberiuichim the zpretty ci job fails with a diff.

2021-05-13 10:59 UTC, tiberiuichim commented
@tisto yes, it was intentional, to showcase how the job would fail. So, good to go? I'll commit the fix.

2021-05-13 11:03 UTC, tisto commented
@tiberiuichim cool! A failing CI is important before fixing things! Yeah, go ahead with the fix!

2021-05-14 08:29 UTC, tisto commented
@tiberiuichim plone.restapi 8 is released. We could go ahead with this PR when the CI is green. Feel free to rebase with master to drop the py2 builds. Maybe it would make sense to backport this to restapi 7 as well (in case we need to backport other PRs/fixes in the future).

2021-05-23 14:09 UTC, tisto commented on news/1120.feature
> +Format zcml files with collective.zpretty. Add zpretty Github workflow. @tiberiuichim
@tiberiuichim if I recall correctly there is an "internal" category that we can use for this.

2021-05-23 15:26 UTC, tiberiuichim commented
@jenkins-plone-org please run jobs

2021-05-23 16:39 UTC, tisto commented on requirements.txt
> +zpretty
@tiberiuichim it should be sufficient to add the zpretty dependency in buildout only. The other three dependencies are necessary for the bootstrap.

2021-05-23 16:39 UTC, tisto approved these changes

2021-05-23 16:39 UTC, merged