[docs] fix docs-linkcheckbroken task
plone/plone.restapi pull request #1422
Opened 2022-05-09 11:51 UTC by wolbernd

Fixes #1421

2022-05-09 11:51 UTC, mister-roboto commented
@wolbernd thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-05-09 11:53 UTC, wolbernd commented
@stevepiercy the task `docs-linkcheckbroken` doesn't seem to be called in github workflows.

2022-05-17 05:33 UTC, stevepiercy commented
Sorry for the delay in responding.

Let's replace the commented out `test sphinx warnings` job with `make docs-linkcheckbroken`. I would like to catch broken links upstream of the main docs.

https://github.com/plone/plone.restapi/blob/781a7675e6c88de11d5b3c6f48ba10bf04ff46cd/.github/workflows/tests.yml#L73-L75

...would become:

```
      # sphinx linkcheck
      - name: sphinx-linkcheck
        run: if [ "${{ matrix.plone-version }}" == "5.2" ] && [ ${{ matrix.python-version }} == '3.7' ]; then make docs-linkcheckbroken; fi
```

And while we're at it, I think we should bump up the matrix variables to 6.0 and 3.9 in both sphinx tasks, and delete the commented out old command.

2022-05-17 05:34 UTC, stevepiercy requested changes
Quick fix here, and see comment in issue.

2022-05-17 05:34 UTC, stevepiercy commented on news/1421.internal
> +fixed broken make task linkcheckbroken
```suggestion
fixed broken make task docs-linkcheckbroken
```

2022-05-17 07:24 UTC, wolbernd commented
@stevepiercy Added the linkchecker to github workflows

2022-05-17 08:32 UTC, stevepiercy requested changes

2022-05-17 08:32 UTC, stevepiercy commented on .github/workflows/tests.yml
> +        run: if [ "${{ matrix.plone-version }}" == "6.0" ] && [ ${{ matrix.python-version }} == '3.9' ]; then make docs-linkcheckbroken; fi
Although it is slightly out of scope, let's clean up the other sphinx task by removing the comment and bumping plone and python versions to align with the latest:

https://github.com/plone/plone.restapi/pull/1422/files/dfb88d317460c824fa9a99abbcc9320e2e40bc2b..553a4bbde7303296586ca7b67d8c4f4cfa538836#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR59-R60

2022-05-17 10:48 UTC, stevepiercy approved these changes
Thank you!

2022-05-17 10:48 UTC, stevepiercy commented
@jenkins-plone-org please run jobs

2022-05-17 12:18 UTC, merged