Pin Sphinx version and make Netlify happy
plone/plone.restapi pull request #1445
Opened 2022-06-09 05:48 UTC by ksuess

2022-06-09 05:48 UTC, mister-roboto commented
@ksuess thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-06-09 06:36 UTC, tisto approved these changes

2022-06-09 06:41 UTC, ksuess commented on netlify.toml
> +  ignore = "git diff --quiet $BRANCH $HEAD -- ./docs/source/"
Comparing the changes on the branch. This has the effect, that the preview is done or at least kept, even when a further commit to the branch does not include any changes in /docs/source/.

2022-06-09 09:34 UTC, stevepiercy requested changes
We need to test diffs with the new Netlify configuration. See comment.

Also remove obsolete file.

2022-06-09 09:34 UTC, stevepiercy commented on netlify.toml
> +  ignore = "git diff --quiet $BRANCH $HEAD -- ./docs/source/"
The Netlify log says `fatal: bad revision 'pull/1445/head'`:

https://app.netlify.com/sites/plone-restapi/deploys/62a194ddac9c4d0008ab7e5a#L14

It still builds, so maybe it is OK? `¯\_(ツ)_/¯` Or perhaps it builds for every commit, and not only for changes in `/docs/source`? You can test by pushing two trivial commits, one with a change in `/docs/source` only, and one outside.

I also checked the [Netlify logs](https://app.netlify.com/sites/plone-restapi/deploys), and it was building only for changes inside `/docs/source/` up until this change. It's possible it was a one-time fluke.

While we're looking at this directory, can you delete `/docs/requirements.txt`? It has been replaced by `/requirements-docs.txt`.

2023-08-25 06:45 UTC, tisto commented
@stevepiercy @ksuess status?

2023-08-25 07:36 UTC, stevepiercy commented
@tisto I merged master to this branch, fixed merge conflicts, and pushed. Let's see what Netlify builds.

2024-09-05 17:18 UTC, davisagli commented
We switched from Netlify to Read the Docs in #1798, so this is outdated.

2024-09-05 17:18 UTC, closed without merging