WIP: Fix timezone for Locking creation date
plone/plone.restapi pull request #1550
Opened 2022-12-06 14:40 UTC by iFlameing

2022-12-06 19:16 UTC, davisagli requested changes
There are also failing tests. The snapshot of the response for this service needs to be updated to include Z

2022-12-06 19:16 UTC, davisagli commented on src/plone/restapi/services/locking/__init__.py
> +    return datetime.fromtimestamp(timestamp).strftime("%Y-%m-%dT%H:%M:%SZ")
Timestamp is a lock modification timestamp which was created in the local timezone here: https://github.com/zopefoundation/Zope/blob/master/src/OFS/LockItem.py#L95

To get it in UTC, we need to use utcfromtimestamp here:
```suggestion
    return datetime.utcfromtimestamp(timestamp).strftime("%Y-%m-%dT%H:%M:%SZ")
```

2022-12-07 11:50 UTC, jensens commented
@jenkins-plone-org please run jobs

2022-12-08 14:48 UTC, reebalazs commented
@iFlameing tests fixed, please proceed as needed.

2022-12-08 14:50 UTC, jensens approved these changes

2022-12-08 16:44 UTC, merged