Provide a JsonCompatible adapter for RichTextValue objects
plone/plone.restapi pull request #1584
Opened 2023-02-13 16:45 UTC by erral

Fixes #1583

2023-02-13 16:45 UTC, mister-roboto commented
@erral thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-02-14 12:29 UTC, jensens commented
Your solution provides only the rendered safe-HTML. But what if we want to get the raw data from the field, for an editor or alike? This could be any content type as raw, i.e. markdown.  I do not think this implementation is enough. I would expect something like a dict with output, raw and its configured types, i.e something like:
```python
{
    "output": {
        "data": "<p>foo<p>",
        "type": "text/safe-html",
    "raw": {
        "data": "foo",
        "data": "text/plain",
}
```

2023-02-14 12:43 UTC, erral commented
This is the initial draft.

I first checked what happens when you add a simple HTML as a default value of the RichText field. I will test further with some other values.

2023-02-14 22:35 UTC, jensens commented
OK! Since this is not a draft PR nor labels were applied, my understanding was like it is ready for review.

2026-07-30 11:07 UTC, erral commented
I have updated the PR to implement the more generic fallback mechanism discussed in issue #1583.

Instead of adding a new global adapter, I improved the `json_compatible` helper to fall back to the Plone site (`getSite()`) when no context is provided. This allows the existing context-aware converter for `RichTextValue` to work in all scenarios (nested, schema defaults, etc.) while keeping the output format consistent with standard fields.

2026-08-05 22:10 UTC, davisagli requested changes

2026-08-05 22:10 UTC, davisagli commented on news/1583.bugfix
> +[erral]
```suggestion
Fix serialization of RichTextValue objects when an explicit context is not known. @erral
```

2026-08-05 22:10 UTC, davisagli commented on src/plone/restapi/serializer/converters.py
> +    return IJsonCompatible(value, None)
@erral It looks like this adds some overhead every time `json_compatible` is called without a context, because now it has to call getSite and queryMultiAdapter every time.

Maybe it does not have enough impact to matter; I have not measured.

But I think there is an easy way to implement this that avoids that: Add an IJsonCompatible adapter for RichTextValue which calls the existing RichtextDXContextConverter using getSite() as the context. Then we are not adding overhead when we convert other types.

2026-08-06 16:42 UTC, erral commented
@jenkins-plone-org please run jobs

2026-08-06 18:49 UTC, davisagli commented
@jenkins-plone-org please run jobs

2026-08-06 21:02 UTC, davisagli approved these changes

2026-08-06 21:02 UTC, merged