Add `show_revert` property to @history endpoint response
plone/plone.restapi pull request #1592
Opened 2023-03-06 11:06 UTC by sneridagh

We need this for the frontend because we can't rely in "being the last element" for not showing the "Revert to this version" button, since the history elements can be of different nature.

The original template relies in `diff_current_url` property for it, I'm renaming it to a more sensible one, also making it boolean.

Related Volto PR: https://github.com/plone/volto/pull/4471

2023-03-06 11:06 UTC, mister-roboto commented
@sneridagh thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-03-06 11:27 UTC, sneridagh commented
@jenkins-plone-org please run jobs

2023-03-06 12:21 UTC, ericof approved these changes
LGTM

2023-03-06 17:07 UTC, davisagli requested changes
I discussed with @sneridagh; I think we can determine whether to show the link on the frontend only without adding to the API.

2023-03-07 15:53 UTC, sneridagh commented
Reworked it in: https://github.com/plone/volto/pull/4471 so we don't have to rely on a backend setting.

@ericof @davisagli let me know, then we can close this one.

2023-03-07 16:55 UTC, closed without merging