Test on Plone 6.0.3
plone/plone.restapi pull request #1612
Opened 2023-03-31 10:56 UTC by ale-rt

2023-03-31 10:56 UTC, mister-roboto commented
@ale-rt thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-04-01 07:27 UTC, erral commented
@ale-rt test fail because a previously untranslated string was translated into Spanish for 6.0.3.

The translation is correct, so if you fix the.documentation file, tests will pass and we can merge

2023-04-01 07:29 UTC, erral requested changes
Change please the documentation file that creates the test fail, and we can merge

2023-04-02 03:38 UTC, davisagli commented
@ale-rt @erral The version update and test fix were done separately, so I'll close this.

2023-04-02 03:38 UTC, closed without merging