Add querystring_search get method
plone/plone.restapi pull request #1616
Opened 2023-04-04 14:01 UTC by robgietema

See #1252 for details

2023-04-04 14:01 UTC, mister-roboto commented
@robgietema thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-04-05 08:19 UTC, sneridagh approved these changes
LGTM

2023-04-05 08:20 UTC, sneridagh commented
@jenkins-plone-org please run jobs

2023-04-05 08:21 UTC, sneridagh commented
@robgietema Now that I realise, I think the only thing missing is a bit on documentation.

2023-04-05 14:31 UTC, robgietema commented
> @robgietema Now that I realise, I think the only thing missing is a bit on documentation.

Agreed, I did add them but it seems it got lost while merging. I've added the docs again.

2023-04-05 19:39 UTC, stevepiercy requested changes
Minor tweaks to the docs.

2023-04-05 19:39 UTC, stevepiercy commented on docs/source/endpoints/querystringsearch.md
> +    'keywords': 'Plone, plone.restapi, REST, API, Querystring, Search'
Please revert the above changes, and adjust your editor settings.

2023-04-05 19:39 UTC, stevepiercy commented on docs/source/endpoints/querystringsearch.md
> +Call the `/@querystring-search` endpoint with a `POST` or a `GET`. When using the `POST` request you provide a query in the request body:
```suggestion
Call the `/@querystring-search` endpoint with either a `POST` or `GET` request.

When using the `POST` request, provide a query in the request body:
```

2023-04-05 19:39 UTC, stevepiercy commented on docs/source/endpoints/querystringsearch.md
> +When using the `GET` request you provide the query as a json urlencoded string as a parameter.
```suggestion
When using the `GET` request, provide the query as a JSON URL-encoded string as a parameter.
```

2023-04-05 20:18 UTC, davisagli reviewed
LGTM, aside from the doc tweaks that Steve requested

2023-04-06 06:02 UTC, tisto commented on src/plone/restapi/services/querystringsearch/get.py
> -class QuerystringSearchPost(Service):
This is a breaking change I guess. Not saying we can not do a breaking. Just mentioning it here...

2023-04-06 06:03 UTC, tisto commented on src/plone/restapi/services/querystringsearch/get.py
> -class QuerystringSearchPost(Service):
I should scroll down before writing a comment. Please ignore me and sorry for the noise. :)

2023-04-06 07:39 UTC, tisto commented
@jenkins-plone-org please run jobs

2023-04-06 07:47 UTC, tisto commented
@robgietema LGTM! Awesome that we can just add this feature without the need for a new major version. :)

When reading the docs, I was wondering if we could be more explicit about how URL encoding works. We could either add one or two lines on how to do the conversion (e.g. in JavaScript) works or link to existing documentation (risky because it could break in the future):

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI?retiredLocale=de

What do you think? @stevepiercy opinions regarding external links vs inline docs?

I saw that the Volto part (https://github.com/plone/volto/pull/4658) already has been merged. I am around to making a release anytime today.

2023-04-06 08:09 UTC, merged

2023-04-06 08:20 UTC, stevepiercy commented
Whoops, I just saw your comment @tisto after approving the docs.

I agree with your idea. An entry in the Glossary would be preferred, using a standard definition, JavaScript method to do the encoding, and a link to MDN for details and demos. Keeps the main docs clean, while providing a reference that we can use here and other parts of the docs.

I also noticed that we use "URL-encoded", but should it be "URI-encoded"?