Use plone.app.multilingual conditionally
plone/plone.restapi pull request #1643
Opened 2023-05-19 07:32 UTC by folix-01

2023-05-19 07:32 UTC, mister-roboto commented
@folix-01 thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-05-19 13:17 UTC, jensens requested changes

2023-05-19 13:17 UTC, jensens commented on src/plone/restapi/services/configure.zcml
> +        />
While at it, we can drop the outdated condition too.
```suggestion
    <include
        package=".multilingual"
        />
```

2023-05-19 13:18 UTC, jensens commented
Why does it touch many unrelated files?

2023-05-20 10:18 UTC, erral commented
Why is this needed?

plone.restapi master is already Plone 5.x only which already includes p.a.multilingual as a dependency.

2023-05-22 09:54 UTC, folix-01 commented
> Why does it touch many unrelated files?

Because of black I think

2023-05-22 09:55 UTC, folix-01 commented
> Why is this needed?
> 
> plone.restapi master is already Plone 5.x only which already includes p.a.multilingual as a dependency.

Because we need to remove il from the Products.CMFPlone

2023-05-23 09:45 UTC, jensens commented
We remove it as a dep of CMFPlone and add it as a dep on Plone. Thus it becomes a core-addon. Architecture wise this is favorable. At the end, for the user, nothing changed.

2023-07-12 14:27 UTC, jensens approved these changes

2023-07-12 16:04 UTC, jensens commented
@jenkins-plone-org please run jobs

2023-07-12 16:42 UTC, merged