added funtion get_allow_discussion_value
plone/plone.restapi pull request #1655
Opened 2023-06-13 17:35 UTC by Akshat2Jain

### Description

This pr aims to add the function 
```
def get_allow_discussion_value(context, request):
    return getMultiAdapter((context, request), name="conversation_view").enabled()
```
in `dxcontent.py` and `site.py`

### Why

Plone Site serializer and the Dexterity serializer return the same value for the "allow_discussion" field. Rather than duplicating the code,  creating a separate function that can be called by both serializers to set the value consistently.

### This  pr related to the issue mentioned in volto project

fixes https://github.com/plone/volto/issues/4758

2023-06-13 17:35 UTC, mister-roboto commented
@Akshat2Jain thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-06-13 19:49 UTC, wesleybl commented
@Akshat2Jain see if you can create a branch in the repository itself in `plone.restapi`. Github Actions tests were not run, because the PR was made from a fork

2023-06-14 06:17 UTC, Akshat2Jain commented
> @Akshat2Jain see if you can create a branch in the repository itself in `plone.restapi`. Github Actions tests were not run, because the PR was made from a fork

Hey @wesleybl, I don't have access rights to create a branch

2023-06-14 08:02 UTC, stevepiercy commented
To allow tests to run on PRs from forks, we need to update the GitHub Workflows, similar to what we did in Volto: https://github.com/plone/volto/commit/5808b787230d4049632a4d5b14c3b0a80cc86e77

We restricted access across the Plone GitHub organization for members of `Contributors`. See https://community.plone.org/t/gsoc-students-please-focus-on-your-application-restrictions-on-developer-team-access-on-github/17041 for more information.

I created a new issue to deal with the above at https://github.com/plone/plone.restapi/issues/1656

@Akshat2Jain meanwhile would you please add a change log entry, per instructions in https://6.docs.plone.org/contributing/index.html#change-log-entry. Thank you!

2023-06-16 18:55 UTC, jensens requested changes
Please make the code conditional, because soon, for Plone 6.1, plone.app.discussion becomes an optional core addon. It can be absent as a package or not installed via GenricSetup.

2023-06-16 20:40 UTC, wesleybl commented
> It can be absent as a package or not installed via GenricSetup.

@jensens checking if the object has the `allow_discussion` attribute would be more performant than using `is_profile_installed`? Or would a `try/except` be fine?

2023-06-16 20:44 UTC, wesleybl commented
hmm i think checking if the `result` dictionary has `allow_discussion` key would be better.

2023-06-17 10:18 UTC, Akshat2Jain commented
> hmm i think checking if the `result` dictionary has `allow_discussion` key would be better.

I think this will be a more desirable solution approach because the code remains compatible with Plone 6.1  irrespective of whether the plone.app.discussion package is present or not. 

Could you please advise on which approach you recommend and also how to do it? @wesleybl 
Thanks!

2023-06-19 15:56 UTC, wesleybl commented
@Akshat2Jain I think it would be something like:

```python
if "allow_discussion" in result:
    result["allow_discussion"] = get_allow_discussion_value(self.context, self.request)
```

You need to rebase with master before continuing.

2023-06-19 17:07 UTC, Akshat2Jain commented
> @Akshat2Jain I think it would be something like:
> 
> ```python
> if "allow_discussion" in result:
>     result["allow_discussion"] = get_allow_discussion_value(self.context, self.request)
> ```

Yeah! This is also correct but I have done something this. 
```
def has_allow_discussion(result):
    return 'allow_discussion' in result
```
```
 if has_allow_discussion(result):
        result["allow_discussion"] = getMultiAdapter(
            (self.context, self.request), name="conversation_view"
        ).enabled()
```
But this will increase no of lines of code!
@wesleybl 
 
Thanks!

2023-06-22 13:24 UTC, jensens commented
Some remarks:
1. `getMultiAdapter((context, request), name="conversation_view").enabled()` is an expensive call. 
2. in the diff it looks like there is some indent wrong.
3. please DRY in code.

2023-06-23 11:34 UTC, Akshat2Jain commented
@wesleybl . I have made the changes. Can you review it.

2023-06-23 13:07 UTC, wesleybl commented
> Please make the code conditional, because soon, for Plone 6.1, plone.app.discussion becomes an optional core addon.

@jensens since `plone.app.discussion` will no longer be part of the core, I'm wondering if `plone.restapi` should be worrying about it. Could it be that instead of a condition, shouldn't we simply remove the `allow_discussion` handler? Shouldn't `plone.app.discussion` be the one to worry about?

Do we plan to have a `plone.restapi` 9 for Plone 6.1? If not, shouldn't it have, to handle situations like this, and to remove support for Plone 5.2?

2023-06-23 13:20 UTC, wesleybl requested changes
I left some comments. See also that Black and flake8 are failing:

https://github.com/plone/plone.restapi/actions/runs/5355874837/jobs/9714682689?pr=1655

https://github.com/plone/plone.restapi/actions/runs/5355874859/jobs/9714682668?pr=1655

2023-06-23 13:20 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
> +    return getMultiAdapter((context, request), name="conversation_view").enabled()
This function must be outside the `SerializeToJson` class. And be imported into `site.py`. Maybe it's good for the test to stay there too. So the code would look like this:

```python
def get_allow_discussion_value(context, request, result):
    if "allow_discussion" in result:
        result["allow_discussion"] = getMultiAdapter((context, request), name="conversation_view").enabled()
```

2023-06-23 13:20 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
> -
The `get_allow_discussion_value` function call should go here.

2023-06-23 13:20 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
> +     result["allow_discussion"] = get_allow_discussion_value(self.context, self.request)
Wrong place to call the function. See comment above.

2023-06-23 13:20 UTC, wesleybl commented on src/plone/restapi/serializer/site.py
> +    return getMultiAdapter((context, request), name="conversation_view").enabled()
The `get_allow_discussion_value` function must be imported from `dxcontent.py`

2023-06-26 15:26 UTC, jensens commented
Conditional support is fine. It is the same as currently with p.a.iterate, in near future with multilingual and there may add up other packages. Plan is to reduce the Plone core (the packages between plone.base and CMFPlone) and add them as core-addons to the space between CMFPlone and the Plone integration package. Distributions then can choose to have them or not.

2023-07-04 05:50 UTC, Akshat2Jain commented
@wesleybl can you review it?

2023-07-04 15:28 UTC, wesleybl requested changes
Pease make a clone of the repository and put several files in one commit. That way we won't have multiple commits.

Checks at `Some checks were not successful`:

https://github.com/plone/plone.restapi/pull/1655#partial-pull-merging

must pass.

2023-07-04 15:28 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
>  @adapter(IDexterityContent, Interface)
`@implementer` and `@adapter` must be before the `SerializeToJson` class.

2023-07-04 15:28 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
> +    return getMultiAdapter((context, request), name="conversation_view").enabled()
The assignment of `result["allow_discussion"]` must be conditional. see my suggestion at:

https://github.com/plone/plone.restapi/pull/1655#discussion_r1239804188

2023-07-04 15:28 UTC, wesleybl commented on src/plone/restapi/serializer/dxcontent.py
> +        result["allow_discussion"] = get_allow_discussion_value(self.context, self.request)
The assignment of `result["allow_discussion"]` must be conditional. see my suggestion at:

https://github.com/plone/plone.restapi/pull/1655#discussion_r1239804188

```suggestion
        get_allow_discussion_value(self.context, self.request, result)
```

2023-07-05 09:30 UTC, Akshat2Jain commented
@wesleybl . I have made the changes. 
Can you tell me where exactly black test are failing

2023-07-05 12:41 UTC, wesleybl commented
@Akshat2Jain the github action output itself says what needs to be changed. to see:

https://github.com/plone/plone.restapi/actions/runs/5462642539/jobs/9942277773?pr=1655#step:5:20

But ideally, you have `black` installed locally, and format the code before committing. You can install it by running the `make` command inside the `plone.restapi` folder. After running `make`, you can run `make black`. This will automatically format the code for you. Some IDEs also have integration with `black`, to format the code when saving.

The `make` command will also install all of the package's dependencies. Then you can run the tests locally, with the command `make test`.

2023-07-05 13:00 UTC, wesleybl requested changes

2023-07-05 13:00 UTC, wesleybl commented on src/plone/restapi/serializer/site.py
> +        result["allow_discussion"] = get_allow_discussion_value(self.context, self.request, result)
The assignment is being done inside the function. So we shouldn't do assignment here.

```suggestion
        get_allow_discussion_value(self.context, self.request, result)
```

2023-07-05 16:35 UTC, stevepiercy commented
> But ideally, you have `black` installed locally, and format the code before committing. You can install it by running the `make` command inside the `plone.restapi` folder. After running `make`, you can run `make black`. This will automatically format the code for you. Some IDEs also have integration with `black`, to format the code when saving.
> 
> The `make` command will also install all of the package's dependencies. Then you can run the tests locally, with the command `make test`.

This should go into the documentation: https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html. It's not in the README. At the very least, an output of the `make help` command would be good.

2023-07-06 09:33 UTC, Akshat2Jain commented
> But ideally, you have `black` installed locally, and format the code before committing. You can install it by running the `make` command inside the `plone.restapi` folder. After running `make`, you can run `make black`. This will automatically format the code for you. Some IDEs also have integration with `black`, to format the code when saving.
> 
> The `make` command will also install all of the package's dependencies. Then you can run the tests locally, with the command `make test`.

I have run the `make black` and it formatted around 93 files. Should I commit all those files? @wesleybl

2023-07-06 12:07 UTC, wesleybl commented
> I have run the make black and it formatted around 93 files. Should I commit all those files? @wesleybl

It shouldn't format so many files. What version of `black` is he using? Please show the command output:

```shell
./bin/black --version
```

Can you please also inform the output of `make black`?

2023-07-06 12:51 UTC, Akshat2Jain commented
> It shouldn't format so many files. What version of `black` is he using? Please show the command output:
> 
> ```
> ./bin/black --version
> ```

> Can you please also inform the output of `make black`?


@wesleybl 
Version
```
black, 23.3.0 (compiled: yes)
Python (CPython) 3.10.6
```
output of `make black`


```
All done! ✨ 🍰 ✨
93 files formatted, 302 files left unchanged.
```

2023-07-06 13:11 UTC, wesleybl commented
@Akshat2Jain  the Makefile is installing the latest from `black`:

https://github.com/plone/plone.restapi/blob/815dbb6ecc0ed87af0dac1c8aa1d7679e2bdfd30/Makefile#L47

Meanwhile, CI is installing version of `versions.cfg`:

https://github.com/plone/plone.restapi/blob/9097cfcb55a7b2a045a5c5e66c46cd04300798c2/.github/workflows/black.yml#L25

Would you like to do another PR, to install the version of black and click that is in versions.cfg?

You could also upgrade to the latest versions of click and black in versions.cfg

You need to update your fork's master branch with the original repository's master branch first.

2023-07-17 14:32 UTC, wesleybl requested changes
Tests are failing. At the end of the CI tracebak it indicates the error. For example:

https://github.com/plone/plone.restapi/actions/runs/5572932135/jobs/10179541947?pr=1655#step:10:789

You can run the tests locally with make test

2023-07-18 06:05 UTC, Akshat2Jain commented
> Tests are failing. At the end of the CI tracebak it indicates the error. For example:
> 
> https://github.com/plone/plone.restapi/actions/runs/5572932135/jobs/10179541947?pr=1655#step:10:789
> 
> You can run the tests locally with `make test`

while running `make test` I am getting this error 
```

bin/test
/bin/bash: line 1: bin/test: No such file or directory
make: *** [Makefile:76: test] Error 127
```
@wesleybl

2023-07-18 09:22 UTC, stevepiercy commented
@Akshat2Jain did you issue the command from the root of the Volto repository?

2023-07-18 09:36 UTC, Akshat2Jain commented
> @Akshat2Jain did you issue the command from the root of the Volto repository?

did you mean from the root of `plone.restapi`

2023-07-18 09:37 UTC, stevepiercy commented
Oops, yes. Sorry, I am multitasking.

2023-07-18 09:40 UTC, stevepiercy commented
Actually, I tried `make test`, and got the same result as you.

So I issued just `make`, and it is installing the package and its dependencies. When it is complete, I will run `make test` again, and report back the results.

2023-07-18 09:59 UTC, stevepiercy commented
`make test` runs the tests for me. Perhaps try again with `make clean`, then `make`, and finally `make test`?

2023-07-18 10:15 UTC, Akshat2Jain commented
> `make test` runs the tests for me. Perhaps try again with `make clean`, then `make`, and finally `make test`?
Yup, Now it is running but I don't know why, I did these steps 2-3 times and at that time it was not running for me.

2023-07-18 11:36 UTC, stevepiercy requested changes
I reviewed only the news item. It still needs review by a maintainer.

2023-07-18 12:47 UTC, wesleybl commented
@jensens @sneridagh a test was made to try to verify that `plone.app.discussion` is installed:

https://github.com/plone/plone.restapi/blob/d819614d6826cbfbff1cf71f5c1e4e2dc9d06f07/src/plone/restapi/serializer/dxcontent.py#L44

However, when `plone.app.discussion` is installed and enabled globally, but a content doesn't have the behavior, `allow_discussion` is not added to the json. This test failed:

https://github.com/plone/plone.restapi/blob/04e69827e9f8f935b0091a50096f780d2363b13c/src/plone/restapi/tests/test_dxcontent_serializer.py#L579

See:

https://github.com/plone/plone.restapi/actions/runs/5586686877/jobs/10211032234?pr=1655#step:10:33

Any other test to see if `plone.app.discussion` is installed would be more costly, and would have to be done on every request.

So I ask, is it ok if we don't have the `allow_discussion` key in this situation?

2023-07-21 15:05 UTC, wesleybl commented
@jensens @sneridagh any opinions here?

2023-07-25 12:37 UTC, wesleybl commented
@davisagli any opinions here? See comment on @jensens' review and https://github.com/plone/plone.restapi/pull/1655#issuecomment-1640150326.

2023-07-30 11:38 UTC, Akshat2Jain commented
@davisagli @jensens any suggestions? we are close to completing this

2023-08-01 10:20 UTC, closed without merging

2023-08-01 14:04 UTC, wesleybl commented
@Akshat2Jain you can reset this commit:

https://github.com/plone/plone.restapi/commit/b7c9acf0ff49c51997935e7fbc31a0e65c96bc25

But if you think it's better, you can create a new branch and a new PR.