Allow PRs from forks to run tests
plone/plone.restapi pull request #1659
Opened 2023-06-14 16:24 UTC by Akshat2Jain

### Description

This pr aims to allow tests to run on PRs from forks

### How

- putting `pull_request` in on in all `.yml` files here:
- ` if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name` in all jobs.

This pr is reated to isse #1656

2023-06-14 16:24 UTC, mister-roboto commented
@Akshat2Jain thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-06-14 17:22 UTC, wesleybl requested changes

2023-06-14 17:22 UTC, wesleybl commented on .github/workflows/black.yml
> +    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
I think it's better for the test to be the first thing in the job.

2023-06-14 17:22 UTC, wesleybl commented on .github/workflows/update_remote_docs.yml
> +
These lines can be removed. The update must be done only in the push on the master.

2023-06-14 17:24 UTC, wesleybl requested changes
Please add an internal entry in changes.

2023-06-15 09:58 UTC, Akshat2Jain commented
Hey @wesleybl, I have made the changes. Can you review it.

2023-06-15 12:37 UTC, wesleybl requested changes

2023-06-15 12:37 UTC, wesleybl commented on news/1659.internal
> +allow tests to run on PRs from forks @akshat2jain
Use the issue id (1656) in the file name.

```suggestion
Allow GHA tests to run on PRs from forks. @Akshat2Jain
```

2023-06-15 12:49 UTC, wesleybl commented on .github/workflows/update_remote_docs.yml
> +    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
Here this line can be removed, as this job does not run in PR.

2023-06-15 17:32 UTC, wesleybl commented on .github/workflows/black.yml
> +
Please, do not add spaces on the lines.

2023-06-15 18:13 UTC, Akshat2Jain commented
Now I think, Its good to go @wesleybl .

2023-06-15 21:03 UTC, wesleybl requested changes

2023-06-15 21:03 UTC, wesleybl commented on .github/workflows/black.yml
> -
Please do not remove line spacing. The spacing must be keep as it was before.

2023-06-16 13:00 UTC, Akshat2Jain commented
@wesleybl Can you review it again? Thanks.

2023-06-16 15:02 UTC, wesleybl approved these changes
LGTM

2023-06-16 16:52 UTC, Akshat2Jain commented
> @Akshat2Jain by having several commits, I suspect that you were making the commits through the github website. I recommend that next time, you make a clone of the repository and put several files in one commit. That way we won't have multiple commits.

Yeah, I will keep that in mind!
Thank You

2023-06-16 23:38 UTC, davisagli approved these changes
@Akshat2Jain @wesleybl Thanks, this looks good!

2023-06-16 23:38 UTC, merged