Resolve version constraints for black package installation
plone/plone.restapi pull request #1671
Opened 2023-07-14 11:51 UTC by Akshat2Jain

### This pull request introduces several updates and improvements to the codebase. Here is a summary of the changes:

- Created a new constraints.txt file.
- Updated the Makefile and CI configuration file to use the constraints.txt file for installing black.
- Modified the CI workflow to include the installation of black using the -c constraints.txt flag.

This Pr is related to the #1668

2023-07-14 11:51 UTC, mister-roboto commented
@Akshat2Jain thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-07-14 11:52 UTC, Akshat2Jain commented
@wesleybl, Can you review it?

2023-07-14 12:30 UTC, wesleybl requested changes
The black CI is failing:

https://github.com/plone/plone.restapi/pull/1671#partial-pull-merging

2023-07-14 12:30 UTC, wesleybl commented on .github/workflows/black.yml
>          run: pip install click==$(awk '/^click =/{print $NF}' versions.cfg) black==$(awk '/^black =/{print $NF}' versions.cfg)
You must replace these lines. Not add others.

2023-07-14 12:32 UTC, wesleybl commented
Please remove [versions.cfg](https://github.com/plone/plone.restapi/blob/master/versions.cfg) file.

2023-07-14 12:37 UTC, Akshat2Jain commented
@wesleybl, Can you check constraints.txt once, is there something to add?

2023-07-14 13:06 UTC, wesleybl commented
@Akshat2Jain the error gives you a hint. Click `Details` on the black error in: https://github.com/plone/plone.restapi/pull/1671#partial-pull-merging

2023-07-14 13:35 UTC, Akshat2Jain commented
Flake 8 is failing, Do I have to do the same as black

2023-07-14 17:50 UTC, wesleybl approved these changes
LGTM

2023-07-14 18:16 UTC, davisagli approved these changes
Thanks!

2023-07-14 18:28 UTC, merged

2023-07-17 13:12 UTC, polyester commented
@wesleybl sure, no problem and done.

2023-07-17 13:28 UTC, Akshat2Jain commented
@wesleybl @polyester @fredvd Thank You, guys!