Cleanup robot tests
plone/plone.restapi pull request #1720
Opened 2023-10-07 08:09 UTC by gforcada

It was not running for quite a long time ago already.

2023-10-07 08:09 UTC, mister-roboto commented
@gforcada thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-10-14 00:13 UTC, davisagli requested changes

2023-10-14 00:13 UTC, davisagli commented on news/1.bugfix
This should be named 1720.bugfix, not 1.bugfix. With the latter, towncrier will put a link to #1 in the generated changelog.

2023-10-14 00:13 UTC, davisagli commented on news/1.bugfix
Actually I would call it 1720.internal

2023-10-14 10:45 UTC, gforcada commented on news/1.bugfix
Thanks, done :)

2023-10-14 14:44 UTC, davisagli commented
@gforcada Tests are failing because there are still imports from plone.app.robotframework

2023-10-14 17:07 UTC, gforcada commented
Actually not in `plone.restapi` but on `plone.app.event` and `plone.app.contenttypes` 😅

As this repository is still not `plone/meta` enabled, and it might take some time for it, at least parts of it, specially the testing part as this repo still supports Plone 5.2, it's a bit hard to fix.

We can keep the dependency here, to avoid the breakage, it does not feel clean, but at least works, hopefully 🍀

2023-10-14 17:59 UTC, davisagli commented
@gforcada I'm trying it with plone.restapi's `test` extra depending on `plone.app.contenttypes[test]`

2023-10-14 17:59 UTC, tisto approved these changes
Wow. I had no clue we still had this dependency in there. Thank you for cleaning up @gforcada!

2023-10-14 17:59 UTC, davisagli commented
@jenkins-plone-org please run jobs

2023-10-14 18:05 UTC, davisagli approved these changes

2023-10-14 18:24 UTC, tisto commented
@gforcada @davisagli did you folks run into this while trying Python 3.12 or rather the robotframework cleanup?

I just started a branch here:

https://github.com/plone/plone.restapi/pull/1722

and I was about to remove p.a.robotframework and friends because they cause trouble. I just want to avoid that we work on this at the same time...If that's the case I am happy to stop my efforts...

2023-10-14 18:25 UTC, davisagli commented
@tisto I will merge this PR as soon as the jenkins builds finish.

2023-10-14 18:51 UTC, merged

2023-10-14 23:02 UTC, gforcada commented
@davisagli thanks! 😄