Make Teaser blocks dynamic
plone/plone.restapi pull request #1788
Opened 2024-05-16 18:21 UTC by pbauer

PLIP: https://github.com/plone/volto/issues/6023
Depends on https://github.com/plone/volto/pull/6024 but should not break anything without it.

2024-05-16 18:21 UTC, mister-roboto commented
@pbauer thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-05-27 09:41 UTC, sneridagh commented
@jenkins-plone-org please run jobs

2024-05-27 11:17 UTC, jensens commented on src/plone/restapi/serializer/blocks.py
> +    match = re.search("resolveuid/([^/]+)", url)
Hint: a global `re.compile` before save CPU-cycles.

2024-05-30 14:40 UTC, sneridagh commented
@pbauer could you take care of Jens suggestion?
@davisagli could you please take a look?

2024-06-10 10:04 UTC, pbauer commented
@jenkins-plone-org please run jobs

2024-06-10 13:27 UTC, jensens approved these changes

2024-06-12 05:44 UTC, davisagli requested changes
This needs tests. I have some in a project that I might be able to adapt.

2024-06-12 05:49 UTC, davisagli commented on src/plone/restapi/serializer/blocks.py
> +    order = 0
Note to self: test whether this also works for teasers inside a grid. The resolveuid transform at the top level might happen too early and resolve the URLs in nested blocks before this runs there.

2024-06-12 21:24 UTC, davisagli commented on news/1788.feature
> +Make Teaser blocks dynamic @pbauer
```suggestion
Added TeaserBlockSerializer which updates the contents of a teaser block from its target if the block has `"overwrite": false`. @pbauer, @davisagli
```

2024-06-12 21:25 UTC, davisagli approved these changes

2024-06-12 21:27 UTC, davisagli commented
@jenkins-plone-org please run jobs

2024-06-12 22:59 UTC, merged

2024-06-14 09:52 UTC, tisto commented
@pbauer @davisagli good work! Shall we make a release with this new feature?

I am wondering if a major release would make it easier for us to keep things in sync with the Volto 18 release which this feature will be shipped with, right @sneridagh?

2024-06-14 09:55 UTC, sneridagh commented
Yes, the plan is to have it paired with 18 and 6.1. I'm ok with a major, up to you though. 

We need a release asap, so we can have the Volto side merged. I plan to work on it during the sprint.

2024-06-15 05:15 UTC, tisto commented
I gave this some thought and I will release a feature release. For "internal" packages it makes lots of sense to stick with strict semantic versioning.

2024-06-15 06:00 UTC, tisto commented
@pbauer @davisagli @sneridagh FYI: I released this with p.restapi 9.7.0: https://pypi.org/project/plone.restapi/9.7.0/