fix #1802 and #1803
plone/plone.restapi pull request #1804
Opened 2024-08-30 09:38 UTC by sauzher

2024-08-30 09:38 UTC, mister-roboto commented
@sauzher thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-08-30 10:30 UTC, stevepiercy requested changes
I only reviewed the news item. This needs a technical review.

2024-08-30 10:30 UTC, stevepiercy commented on news/1802.bugfix
> +Fixes adding JWT plugin
This is more explicit, and gives you credit for the fix.

```suggestion
Fixed implementation of the `jwt_auth` plugin. It now can be added, and its properties, `use_keyring` and `store_tokens`, can be updated. @sauzher
```

2024-08-30 10:30 UTC, stevepiercy commented on news/1802.bugfix
> +Fixes changing plugin properties
Merged with above.

```suggestion
```

2024-09-02 09:52 UTC, stevepiercy approved these changes
News looks good. Needs a technical review.

2024-09-04 01:38 UTC, davisagli approved these changes
@sauzher Thanks!

2024-09-04 01:38 UTC, davisagli commented
@jenkins-plone-org please run jobs

2024-09-04 02:18 UTC, merged