In @vocabulary endpoint, call the vocabulary factory with the 'title'…
plone/plone.restapi pull request #1807
Opened 2024-09-04 15:54 UTC by tiberiuichim

… field from the request form

2024-09-04 15:54 UTC, mister-roboto commented
@tiberiuichim thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-09-04 18:47 UTC, davisagli requested changes

2024-09-04 18:47 UTC, davisagli commented on src/plone/restapi/services/vocabularies/get.py
> +        vocabulary = factory(self.context, query=query)
@tiberiuichim This won't work with many vocabularies, which is why a lot of tests broke.

The IVocabularyFactory interface specifies that a vocab factory is called with a context, but not other parameters: https://github.com/zopefoundation/zope.schema/blob/master/src/zope/schema/interfaces.py#L1087

The addition of the `query` parameter seems to be something that was made up for the vocabulary factories in plone.app.vocabularies.principals without following any formal interface. This makes it hard to detect here how the factory is supposed to be called.

To really sort this out, we need to define a new interface like IQueryableVocabularyFactory. Then plone.app.vocabularies can define that these vocabulary factories implement that interface, and plone.restapi can be updated to pass the query to factories which provide that interface.

2024-09-05 05:39 UTC, tiberiuichim commented
@davisagli what's your feeling on the low-tech approach, only pass the query parameter if it exists in the request?

With this change I can use the SelectAutocomplete widget to search and select users. I can understand your feeling about "use a custom endpoint", but it would be a lot more work than just these 3 changed lines, which are legitimate in filling a gap in Plone - Volto compatibility.

2024-09-05 05:40 UTC, davisagli commented
> what's your feeling on the low-tech approach, only pass the query parameter if it exists in the request?

Is there some mechanism to make sure that it is only sent in the request for the vocabularies that support it?

2024-09-05 05:42 UTC, tiberiuichim commented
No, the simple guard doesn't work, we have to implement your approach. I was hoping to limit the "damage" to plone.app.restapi, but it looks like it will need work in plone.app.vocabularies as well

2024-09-05 05:50 UTC, davisagli commented
@tiberiuichim My approach is probably possible to do in plone.restapi only, if it imports and applies a custom interface to these vocabularies at import time, and checks for it at runtime.

2024-09-05 06:17 UTC, tiberiuichim commented
I'll try a different approach. I'll implement my own custom vocabulary, based on the p.a.v.Principals, which would properly use the serializer API approach in plone.restapi. This would mean that this PR wouldn't be needed anymore

2024-09-05 06:24 UTC, davisagli commented
@tiberiuichim Okay, I'll close this for now

2024-09-05 06:24 UTC, closed without merging