Safely convert items to IContentListingObject
plone/plone.restapi pull request #1810
Opened 2024-09-12 12:34 UTC by erral

Fixes #1809

2024-09-12 12:34 UTC, mister-roboto commented
@erral thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-09-12 12:47 UTC, erral commented
@jenkins-plone-org please run jobs

2024-09-20 23:18 UTC, davisagli requested changes

2024-09-20 23:18 UTC, davisagli commented on src/plone/restapi/serializer/summary.py
> +            return {}
Doesn't this just make it less obvious what the problem is? As a consumer of the API, I would find it surprising to see an empty object in a list of items, and I would wonder what happened. Better to throw the error that happens now, I think.

2024-10-10 15:05 UTC, closed without merging