Use existing aliases controlpanel permissions for aliases endpoint
plone/plone.restapi pull request #1825
Opened 2024-10-15 14:02 UTC by jackahl

fix for #1820

permissions are taken from https://github.com/plone/Products.CMFPlone/blob/f7f0b19197da7917db154cbb383bede97e1a90a7/Products/CMFPlone/controlpanel/permissions.zcml#L82

----
📚 Documentation preview 📚: https://plonerestapi--1825.org.readthedocs.build/

2024-10-15 15:33 UTC, jackahl commented
@jenkins-plone-org please run jobs

2024-10-15 23:23 UTC, davisagli requested changes

2024-10-15 23:23 UTC, davisagli commented on src/plone/restapi/services/aliases/configure.zcml
> +      permission="Products.CMFPlone.ManageContextAliases"
This one is on the site root so:

```suggestion
      permission="Products.CMFPlone.ManagePortalAliases"
```

2024-10-16 08:04 UTC, jackahl commented
@jenkins-plone-org please run jobs

2024-10-16 09:06 UTC, jackahl commented
@jenkins-plone-org please run jobs

2024-10-16 15:32 UTC, davisagli approved these changes
Thanks. The failing jenkins tests are unrelated. I'll merge.

2024-10-16 15:32 UTC, merged