Handle parentheses search queries
plone/plone.restapi pull request #1828
Opened 2024-10-25 09:48 UTC by tedw87

This PR introduces a fix to handle parentheses  in the search functionality.
There is an error when query contains parantheses.
`ParseError
Token <Token:EOF> required, '(' found`

2024-10-25 09:49 UTC, mister-roboto commented
@tedw87 thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-10-25 10:29 UTC, stevepiercy requested changes
Use correct terminology.

2024-10-25 10:29 UTC, stevepiercy commented on news/1828.bugfix
> +Fix error when search query contains parantheses. @tedw87
```suggestion
Removed parentheses from search query. @tedw87
```

2024-10-25 10:29 UTC, stevepiercy commented on src/plone/restapi/search/handler.py
> +        # Escape parentheses by adding backslashes before them
This is not escaping, but removing.

```suggestion
        # Remove parentheses from the query
```

2024-10-25 10:31 UTC, stevepiercy approved these changes
LGTM, but this PR needs a technical review. Thank you!

2024-10-29 00:08 UTC, davisagli requested changes
Please replace parentheses with a space rather than an empty string. a query like `foo(bar)` should be sanitized to `foo bar` to keep the terms separate, not `foobar`.

I would also like to have a test for this scenario.

2024-10-30 19:25 UTC, davisagli commented on news/1828.bugfix
> +Removed parentheses from search query. @tedw87
```suggestion
`@search` service: Remove parentheses from search query. @tedw87
```

2024-10-30 19:26 UTC, davisagli approved these changes

2024-10-30 19:26 UTC, davisagli commented
@jenkins-plone-org please run jobs

2024-10-30 20:43 UTC, merged